name: Beelder-Deploy-Pipeline
on:
  pull_request:
    branches: [master]

permissions:
  id-token: write
  contents: read# This is required for actions/checkout@v2

jobs:
  pull_request:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "Mona The Octocat"
    steps:
      - name: bash-version
        run: echo "::add-mask::$MY_NAME"