name: Beelder-Deploy-Pipeline

permissions:
  id-token: write
  contents: read  #This is required for actions/checkout@v2

on: 
  push:
    branches: [master]

jobs:
  pull_request:
    runs-on: ubuntu-lates
    steps:
      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::133610437896:role/Github
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: my-step-2
        run: |
          echo ${{ secrets.AWS_DEFAULT_REGION }} | sed 's/./& /g'