name: Beelder-Deploy-Pipeline
on:
  pull_request:
    branches: [master]

permissions:
  id-token: write
  contents: read# This is required for actions/checkout@v2

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"