name: Beelder-Deploy-Pipeline

permissions: read-all|write-all

on: 
  push:
    branches: [master]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::133610437896:role/Github
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./build/git_update.sh -v patch

      - name: Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nestjs-template
          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: my-step-2
        run: |
          echo ${{ secrets.AWS_DEFAULT_REGION }} | sed 's/./& /g'