name: Beelder-Deploy-Pipeline

permissions:
  id-token: write
  contents: read  #This is required for actions/checkout@v2

on: 
  push:
    branches: [master]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: my-step-1
        run: echo "Hello World!"
      - name: my-step-2
        run: |
          echo ${{ secrets.AWS_DEFAULT_REGION }} | sed 's/./& /g'