name: Beelder-Deploy-Pipeline

permissions:
  id-token: write
  contents: read# This is required for actions/checkout@v2

on: 
  push:
    branches: [master]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"